#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalInventoryModel

#include "Basic.hpp"

#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalInventoryModel.BP_PalInventoryModel_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_PalInventoryModel_C final : public UPalUIInventoryModel
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PalInventoryModel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PalInventoryModel_C")
	}
	static class UBP_PalInventoryModel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PalInventoryModel_C>();
	}
};
DUMPER7_ASSERTS_UBP_PalInventoryModel_C;

}

