#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Quest_Objective

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Quest_Objective.WBP_Quest_Objective_C.Setup
// 0x0030 (0x0030 - 0x0000)
struct WBP_Quest_Objective_C_Setup final
{
public:
	class FText                                   ProgressDesc;                                      // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Progress;                                          // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_Quest_Objective_C_Setup;

}

