#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WorldMap_IconBase_NoDesign

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_WorldMap_IconBase_NoDesign.WBP_WorldMap_IconBase_NoDesign_C
// 0x0050 (0x0458 - 0x0408)
class UWBP_WorldMap_IconBase_NoDesign_C : public UPalUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void(class UWBP_WorldMap_IconBase_NoDesign_C* iconWidget)> OnHovered;   // 0x0410(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_WorldMap_IconBase_NoDesign_C* iconWidget)> OnUnhovered; // 0x0420(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_WorldMap_IconBase_NoDesign_C* iconWidget)> OnClicked;   // 0x0430(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FGuid                                  LocationId;                                        // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCallInternalClickEvent;                          // 0x0450(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IgnoreMask;                                        // 0x0451(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHiding;                                          // 0x0452(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEnableHideOnZoom;                                 // 0x0453(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Is_Filtered_Out;                                   // 0x0454(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalLocationType                              LocationType;                                      // 0x0455(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HidingByZoom;                                      // 0x0456(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ClickEvent();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_WorldMap_IconBase_NoDesign(int32 EntryPoint);
	void GetInvisibleButton(class UWidget** Button);
	void GetIsHiding(bool* Hiding);
	void GetLocationPoint(class UPalLocationPoint** LocationPoint);
	void GetLocationPosition(struct FVector* LocationPosition);
	void GetLocationRotation(struct FQuat* LocationRotation);
	void GetLocationType(EPalLocationType* Type);
	void GetText(class FText* Text);
	void IsIgnoreMask(bool* IsIgnore);
	void OnClicked_Internal();
	void SetEnable(bool Enable);
	void SetFilterState(const TSet<EPalLocationType>& FilterSet);
	void SetIgnoreMask(bool IsIgnore);
	void SetIsHiding(bool Hiding);
	void Setup(class UPalLocationPoint* LocationPoint, const struct FGuid& LocationId_0);
	void Setup_Internal(class UPalLocationPoint* LocationPoint);
	void SetupForceVisibility(bool* bChangedVisibility);
	void UpdateHiddenOnZoom(double NewZoom);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_WorldMap_IconBase_NoDesign_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_WorldMap_IconBase_NoDesign_C")
	}
	static class UWBP_WorldMap_IconBase_NoDesign_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_WorldMap_IconBase_NoDesign_C>();
	}
};
DUMPER7_ASSERTS_UWBP_WorldMap_IconBase_NoDesign_C;

}

