#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalItemListBlock

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalItemListBlock.WBP_PalItemListBlock_C
// 0x0138 (0x0540 - 0x0408)
class UWBP_PalItemListBlock_C : public UPalUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_InventoryListContent_C*            WBP_InventoryListContent;                          // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UClass*                                 ItemSlotButtonClass;                               // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType)> OnLeftClickedAnyContent; // 0x0420(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnMiddleClickedAnyContent; // 0x0430(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType)> OnRightClickedAnyContent; // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnHoverdAnyContent; // 0x0450(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnEndHoveredAnyContent; // 0x0460(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnFocusedAnyContent; // 0x0470(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnUnfocusedAnyContent; // 0x0480(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* createdWidget)> OnCreatedSlotButton; // 0x0490(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FVector2D                              ChildrenPadding;                                   // 0x04A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnDragDetectedAnyContent; // 0x04B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Button)> OnRequestUseItem;     // 0x04C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<EPalItemTypeA>                         FilterTypeA;                                       // 0x04D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<EPalItemTypeB>                         FilterTypeB;                                       // 0x04E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UPalItemSlot*, int32>              SlotMap;                                           // 0x04F0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Add_Item_Container(class UPalItemContainer* TargetContainer, bool IsEnableQuickMove, bool IgnoreEmptySlot);
	void AddItemSlot(class UPalItemSlot* TargetSlot, bool bIsEnableQuickMove, bool bIgnoreEmptySlot);
	void ChangeItemSlotButtonClass(class UClass* NewClass);
	void ClearFiltering();
	void Construct();
	void Create_Item_Slot_Widget(class UPalItemSlot* TargetSlot, bool IsEnableQuickMove, bool IgnoreEmptySlot);
	void Destruct();
	void EditCreatedSlotWidget(class UWBP_PalItemSlotButtonBase_C* createdSlotWidget, class UWidget** editedWidget);
	void ExecuteUbergraph_WBP_PalItemListBlock(int32 EntryPoint);
	void FilteringFromItemTypeA(TArray<EPalItemTypeA>& displayTypesA, bool isEmptySlotDIsplay);
	void FilteringFromItemTypeB(TArray<EPalItemTypeB>& displayItemTypesB, bool isEmptySlotDIsplay);
	void Focus();
	void GetAllItemSlotButtons(TArray<class UWBP_PalItemSlotButtonBase_C*>* slotButtons);
	void GetFocusTarget(class UWidget** NewParam);
	void IsAllSlotEmpty(bool* IsALLEmpty);
	void On_Drag_Detected_Internal(class UWBP_PalItemSlotButtonBase_C* Widget);
	void On_Update_Slot_Internal(class UPalItemSlot* Slot_0);
	void OnEndHoveredSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnFocusedSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnHoveredSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnLeftClickedSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType);
	void OnMiddletClickedSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnRequestUse_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnRightClickedSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType);
	void OnUnfocusedSlot_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void SetListName(const class FText& InName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PalItemListBlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PalItemListBlock_C")
	}
	static class UWBP_PalItemListBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalItemListBlock_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PalItemListBlock_C;

}

