#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InGameMainMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "EPalUIInGameMainMenuTabType_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InGameMainMenu.WBP_InGameMainMenu_C
// 0x00B0 (0x04E0 - 0x0430)
class UWBP_InGameMainMenu_C final : public UPalUserWidgetOverlayUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           CanvasPanel_106;                                   // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_C*                        WBP_MainMenu;                                      // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_bg_C*                     WBP_MainMenu_bg;                                   // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_btn_C*                        WBP_Menu_btn;                                      // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPalUserWidget*                         CurrentContentWidget;                              // 0x0458(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FPalDataTableRowName_UIInputAction     NextTabActionName;                                 // 0x0460(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalDataTableRowName_UIInputAction     PrevTabActionName;                                 // 0x0468(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalDataTableRowName_UIInputAction     CloseMenuActionName;                               // 0x0470(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<EPalUIInGameMainMenuTabType, struct FDataTableRowHandle> TitleMsgIDMap;                     // 0x0478(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          LockCurrentTab;                                    // 0x04C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDisableCancelOnce;                                // 0x04C9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CA[0x6];                                      // 0x04CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class FName QuestId)> OnRequestOpenMap_ByQuest;                    // 0x04D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void AddChildToContentBody(class UPalUserWidget* Widget);
	void AnmEvent_AllOpen();
	void BndEvt__WBP_InGameMainMenu_WBP_Menu_btn_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_InGameMainMenu(int32 EntryPoint);
	void On_Changed_Tab_Index_Event(int32 OldIndex, int32 NewIndex, class UWidget* FocusTargetWidget);
	void On_Unused_Status_Points_Changed(int32 UnusedPoint);
	void On_Update_Player_Status_Point();
	void OnAllNewFlagCleared_PalDex();
	void OnCancelAction();
	void OnInitialized();
	void OnNextTabAction();
	void OnPrevTabAction();
	void OnRequestShowMap(class FName QuestId);
	void OnSetup();
	void Select_Option_Tab();
	void Select_Tab(EPalUIInGameMainMenuTabType TabType);
	void SelectGuildTab();
	void SelectInventoryEquipmentTab();
	void SelectPaldexTab();
	void SelectPalTab();
	void SelectQuestTab();
	void SelectTechnologyTab();
	void Setup_Attention_Dot(EPalUIInGameMainMenuTabType Tab);
	void Setup_Input_Action();
	void SetupAllAttentionDot();
	void SetupBgText(EPalUIInGameMainMenuTabType Type);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InGameMainMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InGameMainMenu_C")
	}
	static class UWBP_InGameMainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InGameMainMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InGameMainMenu_C;

}

