#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuestTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_PanelWidgetChildrenSelectorBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_QuestTab.WBP_QuestTab_C
// 0x0050 (0x04B0 - 0x0460)
class UWBP_QuestTab_C final : public UWBP_PanelWidgetChildrenSelectorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_QuestTab_C;                     // 0x0460(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         HorizontalBox_Tab;                                 // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Main_Menu_Tab_Key_C*               WBP_Tab_Key_L;                                     // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Main_Menu_Tab_Key_C*               WBP_Tab_Key_R;                                     // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Buildup_TabButton_C*               WBP_TabButton_Main;                                // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Buildup_TabButton_C*               WBP_TabButton_Sub;                                 // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDataTableRowHandle                    MainMissionMsgId;                                  // 0x0490(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    SubMissionMsgId;                                   // 0x04A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void BndEvt__WBP_QuestTab_WBP_Tab_Key_L_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
	void BndEvt__WBP_QuestTab_WBP_Tab_Key_R_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature();
	void BndEvt__WBP_QuestTab_WBP_TabButton_Main_K2Node_ComponentBoundEvent_0_SwitchTabTo__DelegateSignature(int32 Index_0);
	void BndEvt__WBP_QuestTab_WBP_TabButton_Sub_K2Node_ComponentBoundEvent_1_SwitchTabTo__DelegateSignature(int32 Index_0);
	void Construct();
	void ExecuteUbergraph_WBP_QuestTab(int32 EntryPoint);
	void OnChangedTabIndex_Internal(int32 OldIndex, int32 NewIndex, class UWidget* FocusTargetWidget);
	void OnInitialized();
	void RegisterPanelWidget(class UPanelWidget** PanelWidget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_QuestTab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_QuestTab_C")
	}
	static class UWBP_QuestTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_QuestTab_C>();
	}
};
DUMPER7_ASSERTS_UWBP_QuestTab_C;

}

