#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalPlayerInventoryScrollList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "WBP_PalItemScrollList_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalPlayerInventoryScrollList.WBP_PalPlayerInventoryScrollList_C
// 0x00A0 (0x05A0 - 0x0500)
class UWBP_PalPlayerInventoryScrollList_C final : public UWBP_PalItemScrollList_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_PalPlayerInventoryScrollList_C; // 0x0500(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPalUIInventoryModel*                   Model;                                             // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<EPalPlayerInventoryType, class UWBP_PalItemListBlock_C*> CategoryBlockMap;                  // 0x0510(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<EPalPlayerInventoryType>               InventoryTypeArray;                                // 0x0560(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void(class UPalItemSlot* SelectedSlot)> OnRequestOpenUseItemPanel;      // 0x0570(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          CanUseSlot;                                        // 0x0580(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_581[0x3];                                      // 0x0581(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalDataTableRowName_UIInputAction     Handle;                                            // 0x0584(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          CanQuickEquip;                                     // 0x058C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowPrice;                                         // 0x058D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58E[0x2];                                      // 0x058E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* SlotButton)> OnTriedEquipSlot; // 0x0590(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Add_Player_Inventory_Block(EPalPlayerInventoryType inventoryType, class UWBP_PalItemListBlock_C** createdBlock);
	void ClearFiltering();
	void Construct();
	void ExecuteUbergraph_WBP_PalPlayerInventoryScrollList(int32 EntryPoint);
	void FilteringFromInventoryType(TArray<EPalPlayerInventoryType>& displayTypes, bool* IsEmptyDisplaySlot);
	void FilteringFromItemTypeA(TArray<EPalItemTypeA>& displayTypesA, bool isEmptySlotDIsplay);
	void FilteringFromItemTypeB(TArray<EPalItemTypeB>& displayTypesB, bool isEmptySlotDIsplay);
	void GetItemSlotButtons(EPalPlayerInventoryType inventoryType, TArray<class UWBP_PalItemSlotButtonBase_C*>* OutSlotButtonArray);
	void OnLeftCllicked(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType);
	void OnTriedEquipSlot_Internal(class UWBP_PalItemSlotButtonBase_C* Widget);
	void Open_Use_Item_Panel(class UWBP_PalItemSlotButtonBase_C* Button);
	void ScrollToCategoryTop(EPalPlayerInventoryType TargetType, class UWidget** TopFocusTarget);
	void Setup(class UPalUIInventoryModel* useModel);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PalPlayerInventoryScrollList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PalPlayerInventoryScrollList_C")
	}
	static class UWBP_PalPlayerInventoryScrollList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalPlayerInventoryScrollList_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PalPlayerInventoryScrollList_C;

}

