#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalItemScrollList

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "WBP_PalCommonScrollList_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalItemScrollList.WBP_PalItemScrollList_C
// 0x00C0 (0x0500 - 0x0440)
class UWBP_PalItemScrollList_C : public UWBP_PalCommonScrollList_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_PalItemScrollList_C;            // 0x0440(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType)> OnLeftClickedSlot; // 0x0448(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnMiddleClickedSlot; // 0x0458(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType)> OnRightClickedSlot; // 0x0468(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnHoveredSlot;    // 0x0478(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnEndHoveredSlot; // 0x0488(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnFocusedSlot;    // 0x0498(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnUnfocusedSlot;  // 0x04A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UClass*                                 BlockClass;                                        // 0x04B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnDragDetectedSlot;   // 0x04C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsDisplayItemInfo;                                 // 0x04D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEnableQuickMoveSlot;                             // 0x04D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D2[0x6];                                      // 0x04D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalItemSlotButtonBase_C*           CachedLastHoveredSlotButton;                       // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalItemSlotButtonBase_C*           CachedNowHoveringSlotButton;                       // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalItemContainer*                      QuickMoveTargetContainer;                          // 0x04E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Button)> OnRequestUseItem;     // 0x04F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void AddItemContainer(class UPalItemContainer* TargetContainer, const class FText& DisplayName, bool IgnoreEmptySlot, class UWBP_PalItemListBlock_C** createdBlock);
	void AddItemSlotArray(TArray<class UPalItemSlot*>& ItemSlotArray, const class FText& DisplayName, bool IgnoreEmptySlot, class UWBP_PalItemListBlock_C** createdBlock);
	void ClearAllChildren();
	void Construct();
	void CreateBlock(class UPalItemContainer* TargetContainer, const class FText& DisplayName, bool IgnoreEmptySlot, class UWBP_PalItemListBlock_C** createdBlock);
	void CreateBlockByItemSlotArray(TArray<class UPalItemSlot*>& ItemSlotArray, const class FText& DisplayName, bool IgnoreEmptySlot, class UWBP_PalItemListBlock_C** createdBlock);
	void CreateEmptyBlock(class UWBP_PalItemListBlock_C** createdBlock);
	void Destruct();
	void ExecuteUbergraph_WBP_PalItemScrollList(int32 EntryPoint);
	void FilteringBySellableItemDataMap(const TMap<class FName, double>& SellableItemDataMap);
	void Focus();
	void GetAllItemSlotButton(TArray<class UWBP_PalItemSlotButtonBase_C*>* Slots);
	void GetFocusTarget(class UWidget** Target);
	void GetLastHoveredSlotButton(class UWBP_PalItemSlotButtonBase_C** SlotButton);
	void HiddenEmptySlot();
	void InitializeArrowVisibility();
	void OnDragDetected_Internal(class UWBP_PalItemSlotButtonBase_C* Widget);
	void OnEndHovered_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnFocused_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnHovered_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnInitialized();
	void OnLeftClicked_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType);
	void OnMiddleClicked_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnRequestUseItem_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void OnRightClicked_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType);
	void OnUnfocused_Internal(class UWBP_PalItemSlotButtonBase_C* buttonBase);
	void SetQuickMoveTargetContainer(class UPalItemContainer* TargetContainer);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PalItemScrollList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PalItemScrollList_C")
	}
	static class UWBP_PalItemScrollList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalItemScrollList_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PalItemScrollList_C;

}

