#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Quest_ForDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Quest_ForDisplay.WBP_Quest_ForDisplay_C
// 0x0048 (0x0478 - 0x0430)
class UWBP_Quest_ForDisplay_C final : public UPalUserWidgetOverlayUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_Quest_C*                           WBP_Quest;                                         // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FPalDataTableRowName_UIInputAction     InputActionName_QuestTracking;                     // 0x0440(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   InputActionHandle_QuestTracking;                   // 0x0448(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FPalDataTableRowName_UIInputAction     InputActionName_QuestShowMap;                      // 0x044C(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   InputActionHandle_QuestShowMap;                    // 0x0454(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	TMulticastInlineDelegate<void(class FName QuestId)> OnRequestShowMap;                            // 0x0458(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FPalDataTableRowName_UIInputAction     NextTabAction;                                     // 0x0468(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalDataTableRowName_UIInputAction     PrevTabAction;                                     // 0x0470(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WBP_Quest_ForDisplay_WBP_Quest_K2Node_ComponentBoundEvent_0_OnClickedQuestButton__DelegateSignature(class UWBP_Quest_ListButton_C* QuestWidget);
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_Quest_ForDisplay(int32 EntryPoint);
	void On_Input_Action_Quest_Tracking();
	void OnInputAction_NextTab();
	void OnInputAction_PrevTab();
	void OnInputAction_ShowMap();
	void OnUpdateTrackingQuestId(const class FName& QuestId);
	void RegisterQuestShowMap();
	void RegisterQuestTrackingAction();
	void Setup(class FName DisplayQuestId);
	void UnregisterQuestTracingAction();
	void UnregisterShowMapAction();

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Quest_ForDisplay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Quest_ForDisplay_C")
	}
	static class UWBP_Quest_ForDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Quest_ForDisplay_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Quest_ForDisplay_C;

}

