#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Paldex_Map

#include "Basic.hpp"

#include "WBP_Paldex_Map_classes.hpp"
#include "WBP_Paldex_Map_parameters.hpp"


namespace SDK
{

// Function WBP_Paldex_Map.WBP_Paldex_Map_C.AddOffset
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 Offset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::AddOffset(const struct FVector2D& Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "AddOffset");

	Params::WBP_Paldex_Map_C_AddOffset Parms{};

	Parms.Offset = std::move(Offset);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.AddZoomRate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  AddZoomRate_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::AddZoomRate(double AddZoomRate_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "AddZoomRate");

	Params::WBP_Paldex_Map_C_AddZoomRate Parms{};

	Parms.AddZoomRate_0 = AddZoomRate_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.AnmEvent_AllTime
// (BlueprintCallable, BlueprintEvent)

void UWBP_Paldex_Map_C::AnmEvent_AllTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "AnmEvent_AllTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.AnmEvent_DayTime
// (BlueprintCallable, BlueprintEvent)

void UWBP_Paldex_Map_C::AnmEvent_DayTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "AnmEvent_DayTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.AnmEvent_NightTime
// (BlueprintCallable, BlueprintEvent)

void UWBP_Paldex_Map_C::AnmEvent_NightTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "AnmEvent_NightTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Day_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Day_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Day_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Paldex_Map_C_BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Day_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Night_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Night_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Night_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Paldex_Map_C_BndEvt__WBP_Paldex_Map_WBP_PalInvisibleButton_Night_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.ClearDistributionCircle
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Paldex_Map_C::ClearDistributionCircle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "ClearDistributionCircle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.ExecuteUbergraph_WBP_Paldex_Map
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::ExecuteUbergraph_WBP_Paldex_Map(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "ExecuteUbergraph_WBP_Paldex_Map");

	Params::WBP_Paldex_Map_C_ExecuteUbergraph_WBP_Paldex_Map Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.IsZoomMax
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsMax                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::IsZoomMax(bool* IsMax)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "IsZoomMax");

	Params::WBP_Paldex_Map_C_IsZoomMax Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsMax != nullptr)
		*IsMax = Parms.IsMax;
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.LoadAndApplyDefaultMaskTexture
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         TargetMaterial                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::LoadAndApplyDefaultMaskTexture(class UMaterialInstanceDynamic* TargetMaterial)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "LoadAndApplyDefaultMaskTexture");

	Params::WBP_Paldex_Map_C_LoadAndApplyDefaultMaskTexture Parms{};

	Parms.TargetMaterial = TargetMaterial;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Paldex_Map_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.OnLoaded_EA50B4624B0D0BBAA2C2429C4AAD87A5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::OnLoaded_EA50B4624B0D0BBAA2C2429C4AAD87A5(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "OnLoaded_EA50B4624B0D0BBAA2C2429C4AAD87A5");

	Params::WBP_Paldex_Map_C_OnLoaded_EA50B4624B0D0BBAA2C2429C4AAD87A5 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.ResetOffset
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Paldex_Map_C::ResetOffset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "ResetOffset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.ResetZoom
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Paldex_Map_C::ResetZoom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "ResetZoom");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.SetDistributionLocations
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPalUIPaldexDistributionLocationStruct&dayTimeLocationStruct                                  (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FPalUIPaldexDistributionLocationStruct&nightTimeLocationStruct                                (BlueprintVisible, BlueprintReadOnly, Parm)
// E_PaldexDistributionTimeType            TimeType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   isNoDistribution                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::SetDistributionLocations(const struct FPalUIPaldexDistributionLocationStruct& dayTimeLocationStruct, const struct FPalUIPaldexDistributionLocationStruct& nightTimeLocationStruct, E_PaldexDistributionTimeType TimeType, bool* isNoDistribution)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "SetDistributionLocations");

	Params::WBP_Paldex_Map_C_SetDistributionLocations Parms{};

	Parms.dayTimeLocationStruct = std::move(dayTimeLocationStruct);
	Parms.nightTimeLocationStruct = std::move(nightTimeLocationStruct);
	Parms.TimeType = TimeType;

	UObject::ProcessEvent(Func, &Parms);

	if (isNoDistribution != nullptr)
		*isNoDistribution = Parms.isNoDistribution;
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.SetupCircleWidget
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Class_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   WorldLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  realSpawnSize                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::SetupCircleWidget(class UClass* Class_0, const struct FVector& WorldLocation, double realSpawnSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "SetupCircleWidget");

	Params::WBP_Paldex_Map_C_SetupCircleWidget Parms{};

	Parms.Class_0 = Class_0;
	Parms.WorldLocation = std::move(WorldLocation);
	Parms.realSpawnSize = realSpawnSize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.SetVisibilityMap
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::SetVisibilityMap(bool IsVisible_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "SetVisibilityMap");

	Params::WBP_Paldex_Map_C_SetVisibilityMap Parms{};

	Parms.IsVisible_0 = IsVisible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Paldex_Map.WBP_Paldex_Map_C.SetZoomRate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Rate                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Paldex_Map_C::SetZoomRate(double Rate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Paldex_Map_C", "SetZoomRate");

	Params::WBP_Paldex_Map_C_SetZoomRate Parms{};

	Parms.Rate = Rate;

	UObject::ProcessEvent(Func, &Parms);
}

}

